organization/urls.py
from django.conf.urls import url
from .views import list_employee, create_employee, list_department, list_designation

from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^employee-list/$', list_employee, name='employee_list'),
    url(r'^employee-create/$', create_employee, name='employee_create'),

    url(r'^department-list/$', list_department, name='department_list'),

    url(r'^designation-list/$', list_designation, name='designation_list'),
]

rosebay_hris/urls.py
from django.conf.urls import *
from django.contrib import admin
from .views import userlogin, login_validation, userlogout
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^', include("dashboard.urls", namespace="dashboard")),
    url(r'^organization/', include("organization.urls", namespace="organization")),
    url(r'^attendance/', include("attendance.urls", namespace="attendance")),
    url(r'^leave-management/', include("leave_management.urls", namespace="leave_management")),
    url(r'^payroll-management/', include("payroll_management.urls", namespace="payroll_management")),

    url(r'^admin/', admin.site.urls),
    url(r'^login/', userlogin, name='login'),
    url(r'^login-validation/', login_validation, name='login_validation'),
    url(r'^logout/', userlogout, name="logout"),
    # url(r'^login/$', auth_views.login, {'template_name': 'login.html'}),
]

userrole/urls.py
from django.conf.urls import url

from userrole.views import set_role

urlpatterns = [
    url(r'^set-role/(?P<pk>[0-9]+)/$', set_role, name='set_role'),
        ]

organization/models.py
from django.db import models

# Create your models here.

organization/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


def list_employee(request):
    alert_level = "success"
    message_tag = "Success!"
    created_information = ""
    extra_message = ""
    if request.GET.get('a'):
        message_tag = "Success!"
        created_information = request.GET.get('a')
        extra_message = "has been created successfully."

    if request.GET.get('u'):
        message_tag = "Success!"
        created_information = request.GET.get('u')
        extra_message = "information was updated successfully."

    demo_data = [
        {
            'photo': 'assets/img/neiha-joshi.jpg',
            'name': 'Neiha Joshi',
            'email': 'neiha.joshi@rosebayconsult.com',
            'status': 'Active',
            'class': 'success',
            'dep': 'Sales and Marketing',
            'd': 'Manager - Commercial Alliances',
            'j': '2 June,2016'
        },
        {
            'photo': 'assets/img/sabnam-tamrakar.jpg',
            'name': 'Sabnam Tamrakar',
            'email': 'sabnam@rosebayconsult.com',
            'status': 'Inactive',
            'class': 'danger',
            'dep': 'Sales and Marketing',
            'd': 'Manager',
            'j': '14 August,2016'
        },
        {
            'photo': 'assets/img/shristi-shakya.jpg',
            'name': 'Shristi Shakya',
            'email': 'shristi@rosebayconsult.com',
            'status': 'Pending',
            'class': 'warning',
            'dep': 'Sales and Marketing',
            'd': 'Marketing Associate',
            'j': '23 August,2016'
        },
        {
            'photo': 'assets/img/udaya-bajracharya.jpg',
            'name': 'Udaya Bajracharya',
            'email': 'udaya@rosebayconsult.com',
            'status': 'Active',
            'class': 'success',
            'dep': 'Sales and Marketing',
            'd': 'Relationship Manager',
            'j': '14 Septemebr,2016'
        }
    ]

    data = {
        'alert_level': alert_level,
        'message_tag': message_tag,
        'created_information': created_information,
        'extra_message': extra_message,
        'demo_data': demo_data,
        'activePage': {'tree': 'OrganizationPage', 'branch': 'employee_list'},
    }
    return render(request, 'organization/employee-list.html', data)


def create_employee(request):
    data = {
        'activePage': {'tree': 'OrganizationPage', 'branch': 'employee_create'},
    }
    return render(request, 'organization/employee-create.html', data)


def list_department(request):
    alert_level = "success"
    message_tag = "Success!"
    created_information = ""
    extra_message = ""
    if request.GET.get('a'):
        message_tag = "Success!"
        created_information = request.GET.get('a')
        extra_message = "has been created successfully."

    if request.GET.get('u'):
        message_tag = "Success!"
        created_information = request.GET.get('u')
        extra_message = "information was updated successfully."

    data = {
        'alert_level': alert_level,
        'message_tag': message_tag,
        'created_information': created_information,
        'extra_message': extra_message,
        'activePage': {'tree': 'OrganizationPage', 'branch': 'department_list'},
    }
    return render(request, 'organization/department-list.html', data)


def list_designation(request):
    alert_level = "success"
    message_tag = "Success!"
    created_information = ""
    extra_message = ""
    if request.GET.get('a'):
        message_tag = "Success!"
        created_information = request.GET.get('a')
        extra_message = "has been created successfully."

    if request.GET.get('u'):
        message_tag = "Success!"
        created_information = request.GET.get('u')
        extra_message = "information was updated successfully."

    data = {
        'alert_level': alert_level,
        'message_tag': message_tag,
        'created_information': created_information,
        'extra_message': extra_message,
        'activePage': {'tree': 'OrganizationPage', 'branch': 'department_list'},
    }
    return render(request, 'organization/designation-list.html', data)

organization/templates/organization/department-list.html
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<div id="content">
    {%if created_information %}
        <div class="alert alert-{{alert_level}}">
            <strong>{{message_tag}}</strong><b> {{created_information}} </b>{{extra_message}}
        </div>
    {% endif %}
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading sm">
                    <h2><strong>Department</strong> list</h2>
                    <label class="color"><em><strong>List of department</strong></em></label>
                <a href="createDepartment" class="btn btn-primary" style="margin-right:15px; float:right;">
                    <i class="fa fa-plus"></i> Add New Department
                </a>
                </header>

                <div class="panel-body">
                    <form>
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-striped"  id="table-example">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Department</th>
                                        <th>Member Count</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody align="center">
                                    <tr>
                                        <td>1</td>
                                        <td>Human Resource</td>
                                        <td>4</td>
                                        <td>
                                            <span class="tooltip-area">
                                                <a href="editDepartment?p=Human Resource" class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></a>
                                                <a href="javascript:void(0)"  class="btn btn-default btn-sm btn-delete" title="Delete"><i class="fa fa-trash-o"></i></a>
                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>IT Department</td>
                                        <td>7</td>
                                        <td>
                                            <span class="tooltip-area">
                                                <a href="editDepartment?p=IT Department" class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></a>
                                                <a href="javascript:void(0)"  class="btn btn-default btn-sm btn-delete" title="Delete"><i class="fa fa-trash-o"></i></a>
                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>Account Department</td>
                                        <td>3</td>
                                        <td>
                                            <span class="tooltip-area">
                                                <a href="editDepartment?p=Account Department" class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></a>
                                                <a href="javascript:void(0)"  class="btn btn-default btn-sm btn-delete" title="Delete"><i class="fa fa-trash-o"></i></a>
                                            </span>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</div>
{% include "delete-models.html" %}
{% endblock %}

{%block extra_script%}

{%endblock%}

organization/templates/organization/designation-list.html
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<div id="content">
    {%if created_information %}
        <div class="alert alert-{{alert_level}}">
            <strong>{{message_tag}}</strong><b> {{created_information}} </b>{{extra_message}}
        </div>
    {% endif %}
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading sm">
                    <h2><strong>Designation</strong> list</h2>
                    <label class="color"><em><strong>List of designation</strong></em></label>
                <div class="header-button">
                <a href="createDesignation" class="btn btn-primary" style="margin-right:15px; float:right;">
                    <i class="fa fa-plus"></i> Add New Designation
                </a>                        </div>
                </header>

                <div class="panel-body">
                    <form>
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-striped"  id="table-example">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Designation</th>
                                        <th>Member</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody align="center">
                                    <tr>
                                        <td>1</td>
                                        <td>Human Resource Manager</td>
                                        <td>1</td>
                                        <td>
                                            <span class="tooltip-area">
                                                <a href="editDesignation?p=Human Resource Manager" class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></a>
                                                <a href="javascript:void(0)"  class="btn btn-default btn-sm btn-delete" title="Delete"><i class="fa fa-trash-o"></i></a>
                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>Programmer</td>
                                        <td>6</td>
                                        <td>
                                            <span class="tooltip-area">
                                                <a href="editDesignation?p=Programmer" class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></a>
                                                <a href="javascript:void(0)"  class="btn btn-default btn-sm btn-delete" title="Delete"><i class="fa fa-trash-o"></i></a>
                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>Project Manager</td>
                                        <td>3</td>
                                        <td>
                                            <span class="tooltip-area">
                                                <a href="editDesignation?p=Project Manager" class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></a>
                                                <a href="javascript:void(0)"  class="btn btn-default btn-sm btn-delete" title="Delete"><i class="fa fa-trash-o"></i></a>
                                            </span>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</div>
{% include "delete-models.html" %}
{% endblock %}

{%block extra_script%}

{%endblock%}

organization/templates/organization/employee-list.html
{% extends "layout.html" %}
{% load staticfiles %}
{% block content %}
<div id="content">
    {%if created_information %}
        <div class="alert alert-{{alert_level}}">
            <strong>{{message_tag}}</strong><b> {{created_information}} </b>{{extra_message}}
        </div>
    {% endif %}
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading sm">
                    <h2><strong>Employee</strong> list</h2>
                    <label class="color"><em><strong>List of employee</strong></em></label>
                    <a href="{% url 'organization:employee_create' %}" class="btn btn-primary" style="margin-right:15px; float:right;">
                        <i class="fa fa-plus"></i> Add New Employee
                    </a>
                </header>

                <div class="panel-body">
                    <form>
                        <div class="table-responsive">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-striped"  id="table-example">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Photo</th>
                                        <th>Name</th>
                                        <th>Employee Id</th>
                                        <th>Email</th>
                                        <th>Department</th>
                                        <th>Designation</th>
                                        <th>Joining Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody align="center">
                                    {%for data in demo_data %}
                                    <tr>
                                        <td>{{forloop.counter}}</td>
                                        <td><img src="{% static data.photo %}" alt="" class="avatar-small"></td>
                                        <td>{{data.name}}</td>
                                        <td>00{{forloop.counter}}</td>
                                        <td>{{data.email}}</td>
                                        <td>{{data.dep}}</td>
                                        <td>{{data.d}}</td>
                                        <td>{{data.j}}</td>
                                        <td widtd="10%">
                                            <span class="tooltip-area">
                                                <a href="editEmployee?p={{data.name}}" class="btn btn-default btn-sm" title="Edit"><i class="fa fa-pencil"></i></a>
                                                <a href="salaryInfo?p={{data.name}}" class="btn btn-default btn-sm" title="Salary Info"><i class="fa fa-money"></i></a>
                                                <a href="viewProfile?p={{data.name}}" class="btn btn-default btn-sm" title="View Profile"><i class="fa fa-eye"></i></a>
                                                <a href="javascript:void(0)"  class="btn btn-default btn-sm btn-delete" title="Delete"><i class="fa fa-trash-o"></i></a>
                                            </span>
                                        </th>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
</div>
{% include "delete-models.html" %}
{% endblock %}

{%block extra_script%}

{%endblock%}